metadata:
        sample_table: LOLAHema_samples_test.csv
        output_dir: $HOME 

derived_attributes: [file_path]
data_sources: 
        source1: /project/shefflab/resources/regions/LOLAHema/{genome}/AML_{protocol}/regions/{file_name}  
